---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server, windows 
summary: SnapCenter サーバインストーラの実行ファイルを使用して、 SnapCenter サーバをアップグレードできます。 
---
= WindowsホストでのSnapCenterサーバのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最新バージョンで提供される最新の機能と拡張機能にアクセスするには、 SnapCenter Server をアップグレードする必要があります。

.開始する前に
* SnapCenterサーバホストにWindowsの更新プログラムが適用されていて、システムの再起動が保留されていないことが必要です。
* アップグレードを開始する前に、他の操作が実行されていないことを確認してください。
* ジョブが実行されていないことを確認した後、 SnapCenterリポジトリ (MySQL) データベースをバックアップします。SnapCenter ServerとExchangeプラグインをアップグレードする前に、これを行っておくことが推奨されます。
+
詳細については、を参照してください link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenterリポジトリのバックアップ"^]。

* SnapCenter Server ホストまたはプラグイン ホスト上の変更されたすべてのSnapCenter構成ファイルをバックアップします。


SnapCenter 構成ファイルの例： SnapDrive Service.exe.config 、 SMCoreServiceHost.exe.config など。

* SnapCenter 5.0 に複数のバージョンのカスタム プラグインをインストールしている場合は、6.0 以降にアップグレードする前に、PowerShell コマンドレットを実行して、以前のバージョンのカスタム プラグイン (最新バージョンを除く) をすべてSnapCenterリポジトリ (NSM データベース) から削除する必要があります。
+
** 走る `Open-SmConnection`SnapCenterAdminロールの資格情報を使用してログインします
** 走る `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
 https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8["SnapCenter 6.0以降へのアップグレードが失敗する"] 。





.タスクの内容
* アップグレード中に、 SnapCenter はSQL スクリプトを実行して NSM データベース内の Exchange データを更新し、DAG とホストの短縮名を FQDN に変換します。これは、Exchange プラグインとともにSnapCenter Server を使用する場合にのみ適用されます。
* サーバー ホストを手動でメンテナンス モードにした場合は、アップグレード後に *ホスト* > *スケジュールのアクティブ化* を選択して、サーバー ホストのメンテナンス モードを解除します。
* SnapCenter Plug-in for Microsoft SQL Server、SnapCenter Plug-in for Microsoft Exchange Server、およびSnapCenter Plug-in for Microsoft Windowsでは、scripts_pathを実行するために、サーバとプラグインホストの両方をバージョン4.7にアップグレードすることを推奨します。
+
ポリシーでプリスクリプトとポストスクリプトが有効になっている既存のバックアップスケジュールと検証スケジュールの場合、バックアップ処理はアップグレード後も引き続き機能します。

+
［*ジョブの詳細*］ページで、スクリプトをscripts_pathにコピーし、ポリシーを編集してscripts_pathに対するパスを指定するように警告メッセージが表示されます。クローンライフサイクルジョブの場合は、サブジョブレベルで警告メッセージが表示されます。



.手順
. NetApp Support Siteから SnapCenter サーバインストールパッケージをダウンロードします。
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. C：\Program Files\NetApp\SnapCenter WebAppにあるweb.configのコピーを作成します。
. アップグレードが失敗した場合に復元できるように、Windows タスク スケジューラからSnapCenterプラグイン ホスト スケジュールをエクスポートします。
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`

. リポジトリのバックアップが設定されていない場合は、 SnapCenter MySQL データベースダンプを作成します。
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`

+
プロンプトが表示されたら、パスワードを入力します。

. ダウンロードした .exe ファイルをダブルクリックして、 SnapCenter Server のアップグレードを開始します。
+
アップグレードを開始すると、 SnapCenter は事前チェックを実行します。システムが最小要件を満たしていない場合、 SnapCenter はエラーまたは警告メッセージを表示します。続行する前にエラーを修正してください。警告を無視して続行できます。

+

NOTE: SnapCenterでは、以前のバージョンのSnapCenterサーバのインストール時に指定した既存のMySQLサーバリポジトリデータベースパスワードが引き続き使用されます。

. *アップグレード*を選択します。
+
どの段階でも「*キャンセル*」を選択すると、 SnapCenter はアップグレードを停止します。  SnapCenterサーバーは以前の状態にロールバックしません。

+
*ベスト プラクティス:* ログアウトして再度ログインするか、新しいブラウザーを開いてSnapCenterユーザー インターフェイスにアクセスします。



.終了後
* sudoユーザを使用してプラグインをインストールする場合は、_C：\ProgramData\NetApp\SnapCenter\Package Repository\SC_UNIX_plugins_checksum.txt_にあるsha224キーをコピーして、_/etc/sudoers_fileを更新する必要があります。
* サーバホスト上のリソースの新規検出を実行する必要があります。
+
SnapCenter にサーバ ホストのステータスが停止として表示される場合は、しばらく待ってから新規検出を実行してください。  *HostRefreshInterval* パラメータの値 (デフォルト値は 3600 秒) を 10 分を超える任意の値に変更することもできます。

* アップグレードが失敗した場合は、失敗したインストールをクリーンアップし、以前のバージョンのSnapCenterを再インストールして、NSM データベースを以前の状態に復元します。
* サーバホストをアップグレードしたら、ストレージシステムを追加する前にプラグインもアップグレードする必要があります。

